import "@/css/main.css";
import Navbar from "@/components/Navbar";

export const metadata = {
  title: "BARBEL | Barber Shop",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
 
       <Navbar />
        {children}
   
      </body>
    </html>
  );
}
